GET http://localhost:8090/usuario/1
Accept: application/json

###

GET http://localhost:8090/usuario/
Accept: application/json

###

POST http://localhost:8090/usuario
Content-Type: application/json
Accept: application/json

{
  "id": 4,
  "nome": "Tassio",
  "email": "d@d.com",
  "senha": "0123"
}